### ISSUE TITLE
Lack features of AMiner

### ISSUE THREAD

**Issue by GooLiang** [jianjianGJ/hgcond#1]
Thanks for your good work.
When I load AMiner dataset, it not contain the .tensor files.
  data['author'].x = torch.load(root+'/AMiner/raw/author.tensor')
  data['paper'].x = torch.load(root+'/AMiner/raw/paper.tensor')
  data['venue'].x = torch.load(root+'/AMiner/raw/venue.tensor')
Can you provide a way to obtain the above files?

**Comment by jianjianGJ** [comment]
Sorry, I overlooked that. I upload it on [google drive](https://drive.google.com/file/d/1KPvn7rCJtY1uCvsRG_fMgD4rhpk5kEtQ/view?usp=sharing)

**Comment by GooLiang** [comment]
Thanks for your help, I would like to know by what method the features on google_drive are generated?

**Comment by jianjianGJ** [comment]
This is a dataset I collected a long time ago. I lost the code for generating features, and I can't remember it clearly. I may have downloaded it from the Internet. You can check [**Latent Vector Representations Learned by metapath2vec & metapath2vec++.](https://ericdongyx.github.io/metapath2vec/m2v.html) **
